version: 0.2

env:
  variables:
    ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
    SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}

phases:
  install:
    commands:
      - echo "[+] Scanning for security vulnerability within dependencies"
      # - pipenv check (if pipenv is installed and a Pipfile is in place)
      # - Alternatively: https://www.owasp.org/index.php/OWASP_Dependency_Check
  pre_build:
    commands:
      - pip install google-cloud-vision

  build:
    commands:
      - echo "[+] Installing dependencies...."
      - pip install -r requirements.txt
      
      # Escrever conteudo de GOOGLE_CREDETIALS para json
      # - echo "${{ secrets.GCP_CREDENTIALS }}" > $pwd/"credenciais-gcp.json"
