version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)
      - COMMIT_HASH=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo Logging in to Docker Hub...
      - docker login -u ${DOCKER_HUB_LOGIN} -p ${DOCKER_HUB_PWD}
      - docker pull ${REPOSITORY_URI}:latest
  build:
    commands:
      - echo Build started on `date`
      - echo Copying files from s3 into project ...
      - CURRENT_PATH=$(pwd)
      - aws s3 sync s3://${VARS_S3_BUCKET}/${APP_NAME_S3_FOLDER}/ ${CURRENT_PATH}/
      - echo Building the Docker image...
      - docker build -t ${REPOSITORY_URI}:latest -t ${REPOSITORY_URI}:${IMAGE_TAG} -f ${CURRENT_PATH}/Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push ${REPOSITORY_URI} --all-tags
